### ISSUE TITLE
Find you class should be a feature

### ISSUE THREAD

**Issue by lsolesen** [vih-elevforening/elevforeningen-build#13]
The "find your class"-pane should be a feature put in the first column on the What's going on page - also even if I revert the features.

**Comment by mglaman** [comment]
@lsolesen should we open a "ef_pages" for custom landing pages? Or add this into ef_deploy? We're going to need to create a new homepage (duplicating one from Commons versus overriding it.)

**Comment by mglaman** [comment]
Also, @lsolesen, I believe whatever action taken from last comment will also affect #10. A lot of the changes made to Commons need to get exported as their own and not be reflected upon Commons directly.

**Comment by lsolesen** [comment]
A new repos would be fine.
Den 19/03/2015 05.06 skrev "Matt Glaman" <notifications@github.com>:

**Comment by mglaman** [comment]
Added Features Override and EF Commons to hold changes to the distribution.
