### ISSUE TITLE
Paid events should be a part of events also in development

### ISSUE THREAD

**Issue by lsolesen** [vih-elevforening/elevforeningen-build#15]
Right now the custom Paid Events are only made on production. I want this in development also, so it is easier to just dive into the development.

**Comment by mglaman** [comment]
So you'd like to create the event in development, and then be able to export it to production? Like using Node Export (https://www.drupal.org/project/node_export). Or would it be best to just keep them as migrated content, so you can import them via the events.csv?

**Comment by lsolesen** [comment]
No. I think I overridden the view for the Events page to also show Paid events. I want this in code, so this is available on every site.
