### ISSUE TITLE
Make sure that people sign into a group

### ISSUE THREAD

**Issue by lsolesen** [vih-elevforening/elevforeningen-build#19]
Make it a requirement to sign up for the student meeting, that you need to be in a group. This should be really easy with redirects, so people are getting placed correctly.

**Comment by mglaman** [comment]
@lsolesen - users will be alerted and sent to the /groups page, with path redirect. I'm not sure how we could tap into areas from there to ensure they get redirected properly to signup page.

**Comment by lsolesen** [comment]
@mglaman As all groups are set to administrator approval, it is enough for people to have a pending status for membership in a group. Did you take this into account with the commit?

**Comment by mglaman** [comment]
Yes, I did. "og_get_groups_by_user" loads all memberships which aren't marked as inactive, and should include pending. I'll double verify - but in all my testing I had a created groups which 1) needed admin approval for group to be active 2) join group waiting for approval (so I could check out for an event.)

**Comment by mglaman** [comment]
I was wrong. Fixed the group membership checks, now.
