### ISSUE TITLE
Enable the join class search block programatically in the right sidebar

### ISSUE THREAD

**Issue by lsolesen** [vih-elevforening/elevforeningen-build#20]
The what's going on page / and the /groups page should have it enabled automatically.

**Comment by mglaman** [comment]
So it should move from being above to the sidebar on What's Going On?

**Comment by lsolesen** [comment]
In production the join clasd is in the right sidebar. Where do you think it
is best?
Den 02/06/2015 17.30 skrev "Matt Glaman" <notifications@github.com>:

**Comment by mglaman** [comment]
I think it is good in the right sidebar. I'll update code export to have it there

**Comment by mglaman** [comment]
This should be set from vih-elevforening/ef_commons@54d6d687c0cf39544b300c1064792378b3980c92
