### ISSUE TITLE
Infinite loop when accessing the event from last year

### ISSUE THREAD

**Issue by lsolesen** [vih-elevforening/elevforeningen-build#25]
https://elevforeningen.vih.dk/groups/jubil-um-og-gensynsweekend-2014

**Comment by mglaman** [comment]
It's the Redirect module. I deleted the one redirect. It happens when changing a title too many times, or something. Here's an issue with RTBC patch (that's been RTBC for years) https://www.drupal.org/node/1796596.

Surprisingly Commons doesn't include it.

**Comment by mglaman** [comment]
Here is a patch against Commons to include Redirect patch, if you'd want to (or wait and see if they merge it in) https://www.drupal.org/node/2502759
