### ISSUE TITLE
Group membership is double on edit-profile page

### ISSUE THREAD

**Issue by lsolesen** [vih-elevforening/elevforeningen-build#26]
See this drupal.org issue: https://www.drupal.org/node/2284965

**Comment by mglaman** [comment]
@lsolesen Should the second one (or both even) be hidden? The second one is for trusted contacts.. but you can't remove anything from it.

**Comment by lsolesen** [comment]
Hm. I think we should improve commons by a patch and simply change the
label?
Den 21/06/2015 06.05 skrev "Matt Glaman" <notifications@github.com>:

**Comment by mglaman** [comment]
Sounds good. I'll write a patch which updates the instance labels

**Comment by mglaman** [comment]
So, I have no idea where the field instance is coming from - it isn't in code and being provisioned somehow. Going to at least commit a features override.

**Comment by mglaman** [comment]
Closing, the field isn't in code and not sure action that should be taken to change it in Commons.
