### ISSUE TITLE
Orders paid in full is not being set to 'Completed' automatically.

### ISSUE THREAD

**Issue by lsolesen** [vih-elevforening/elevforeningen-build#33]
Orders paid in full is not being set to 'Completed' automatically.

https://elevforeningen.vih.dk/admin/commerce/orders

They should be set automatically to Completed --> which in turn sets them to Invoiced by the following rules:

https://elevforeningen.vih.dk/admin/config/workflow/rules/reaction/manage/ef_commerce_update_the_order_status_when_paid_in_full

https://elevforeningen.vih.dk/admin/config/workflow/rules/reaction/manage/rules_commerce_billy_invoice_order_on_completion

**Comment by mglaman** [comment]
So the rule seems to be fine, I wonder if its the captured payment hook.

**Comment by mglaman** [comment]
It's working..however some kind of change is reverting orders back to "pending."

![screen shot 2015-06-20 at 8 41 13 pm](https://cloud.githubusercontent.com/assets/3698644/8270017/c1e1cea8-178c-11e5-88f9-bccccbdb0d51.png)

**Comment by lsolesen** [comment]
This is still happening in production.

**Comment by lsolesen** [comment]
It is as after creating this - it goes back to "Completed" (probably the code added) and is invoiced again.

![skaermbillede 2015-06-24 kl 11 32 08](https://cloud.githubusercontent.com/assets/148026/8326963/3059f9fc-1a65-11e5-829d-9c58a366ba9d.png)

**Comment by mglaman** [comment]
Ugh, so there is a conflicting rule, that's for sure. I thought the one had fixed it

**Comment by mglaman** [comment]
It is that rule, from vih-elevforening/ef_commerce@ae22d838d0f36c176a9190e9c575c2701b88dd58

````

+/**
+ * Implements hook_default_rules_configuration_alter().
+ */
+function ef_commerce_default_rules_configuration_alter(&$data) {
+  if (isset($data['commerce_checkout_order_status_update'])) {
+    $data['commerce_checkout_order_status_update']->active = FALSE;
+  }
+}

````

I manually disabled it, since the hook doesn't want to cooperate.

**Comment by mglaman** [comment]
@lsolesen Features override isn't working on it either. But at least there is an alter to mark it as disabled and is now manually disabled

**Comment by lsolesen** [comment]
@mglaman Did you commit anything for this one? It seems to be working in production now - did you just fix it on the site?

**Comment by mglaman** [comment]
I did a commit before, but the hook wasn't taking place. So there was a manual fix.

vih-elevforening/ef_commerce@ae22d83
