### ISSUE TITLE
Add profile progress block

### ISSUE THREAD

**Issue by lsolesen** [vih-elevforening/elevforeningen-build#5]
Instead of utilizing drupal_set_message() ef_user should create a block giving the user a message to fill in all fields.

**Comment by lsolesen** [comment]
Related to gh-3 and https://www.drupal.org/node/2443749

**Comment by mglaman** [comment]
Do you have some examples that would help in implementing this? Would it be something as simple as a block with a list that looks like a check list, and as each step completes the bullet become a check?

**Comment by lsolesen** [comment]
Just really simple to start out with. Pretty much i want to try to avoid
the set_message() on e.g. the dashboard and have it as a Block i can put
anywhere.
Den 02/06/2015 05.54 skrev "Matt Glaman" <notifications@github.com>:
