### ISSUE TITLE
Add block asking for year if none has been filled

### ISSUE THREAD

**Issue by lsolesen** [vih-elevforening/elevforeningen-build#6]
If the user is not member of any groups, they should be asked for the year!

**Comment by mglaman** [comment]
@lsolesen I think we'll need to discuss this one so I have a better understanding of exact needs

**Comment by lsolesen** [comment]
Elevforeningen is an alumni association. Maybe a user is not part of any groups. Every user should be a member of a group to reflect the year, they were a student at Vejle Idrætshøjskole. If the user is not a part of the group, a block on the fronpage could ask the user to apply for a group.

The block should take into account whether they have a pending application. Is that enough extra info?

**Comment by mglaman** [comment]
Yep! That clears it up more @lsolesen :)

**Comment by mglaman** [comment]
@lsolesen the pane links to /groups and does an autocomplete to find groups.

**Comment by lsolesen** [comment]
I put the block on https://elevforeningen.vih.dk/home. The autocomplete seems to work, but when clicking go I am not redirected to the correct group.

Also the block shows even on a user which belongs to some groups.
