### ISSUE TITLE
Error when trying to create a new user

### ISSUE THREAD

**Issue by lsolesen** [vih-elevforening/elevforeningen-build#9]
On user/register and admin/people/create I get the following:

    EntityMetadataWrapperException: Unable to get the data property thoroughfare as the parent data structure is not set. i EntityStructureWrapper->getPropertyValue() (linje 438 af /data/disk/o5189739716/static/ef-20150314/profiles/commons/modules/contrib/entity/includes/entity.wrapper.inc).

**Comment by lsolesen** [comment]
I also opened it in the Commons issue queue https://www.drupal.org/node/2454471

**Comment by lsolesen** [comment]
@mglaman This is an issue with high priority, as the site is not really functional at the moment, at we are expecting 50 new signups right now.

I created dev.elevforeningen.vih.dk in the Aegir interface and put it on a dev platform, so you can mess around with everything on both the site and the code behind. Thanks!

**Comment by lsolesen** [comment]
As @mglaman suggested on IRC I ran the following on the dev-site

    drush fra --y

That solved this issue, however, it raised a new issue.

**Comment by mglaman** [comment]
@lsolesen I think this was due to ef_users, and I've added some safety measures. Can you test on dev and I think we can close this, then.

**Comment by mglaman** [comment]
Closing, has been ready for dev.
